### ISSUE TITLE
su Chrome scrivete al punto 1- clona il repo - che cosa devo fare e come farlo? 

### ISSUE THREAD

**Issue by alba-77** [gall0ws/freeRep#13]
su Chrome scrivete al punto 1- clona il repo - che cosa devo fare e come farlo? devo installare un'estensione da clonare?

**Comment by gall0ws** [comment]
Per clonare il repo ci si riferiva all'operazione di git `clone` (https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls)

Alternativamente puoi scaricare lo zip[1] e scompattarlo: verrà creata una directory `freeRep-master` che successivamente protrai selezionare da chrome dopo aver clickato su "Load Unpacked".

Il clone è l'opzione consigliata perché rende semplice l'aggiornamento ad una nuova versione, assunto che l'utente finale abbia familiarità con git.

[1] 
![image](https://user-images.githubusercontent.com/3230232/143571192-6429c46c-751f-4da2-ad23-6df90edcc92d.png)

**Comment by alba-77** [comment]
Grazie. Non ho capito come fare il clone ma ci proverò nuovamente. 
Non vorrei farvi perdere ulteriormente tempo.
Se c'è un video ,su youtube o da un'altra parte, che lo mostra vi prego di indicarmelo.
