### ISSUE TITLE
Gli articoli in abbonamento di Repubblica non funzionano

### ISSUE THREAD

**Issue by passthesh3ll** [gall0ws/freeRep#17]
Ho installato l'ultima versione 1.6 come userscript su firefox (os archlinux). Le pagine per abbonati come questa `https://www.repubblica.it/cronaca/2022/01/09/news/zaia_non_reggeremo_faccio_l_ultimo_appello_draghi_ascolti_la_scienza_-333119278/` non mostrnao interamente il testo. È normale?

**Edit**: ho letto meglio il readme, per repubblica funziona solo con l'estensione. Ho provato a configurare https://m.google.it/ come referer sull'estensione BypassPaywall, c'è una config funzionante per bypasspaywall?

**Comment by gall0ws** [comment]
Non conosco BypassPaywall, ma se ti fa cambiare il referer dovrebbe andare. Un'altra cosa che fa l'estensione rispetto all'user script è cancellare i cookie di repubblica, ma questo puoi farlo da firefox stesso: blocca repubblica.it nella sezione "cookies and site data" delle impostazioni.
