### ISSUE TITLE
Non funziona nelle edizioni locali

### ISSUE THREAD

**Issue by NessunoIM** [gall0ws/freeRep#4]
Manca il supporto per i domini di secondo livello delle 10 edizioni locali tipo: https://roma.repubblica.it/cronaca/2021/05/18/news/as_roma_il_papa_di_un_calciatore_entra_a_trigoria_e_spacca_tutto_con_una_spranga-301575223/

Roma, Bari, Palermo, Firenze, Torino etc.

**Comment by gall0ws** [comment]
Rilasciata v1.2 che contiene il fix
